# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vkuser',
            name='tv_series',
            field=models.ManyToManyField(blank=True, related_name='tv_series', to='common.TVSeries'),
        ),
        migrations.AlterUniqueTogether(
            name='tvseriesvariants',
            unique_together=set([('vk_user', 'variants')]),
        ),
    ]
