# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20170501_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvseries',
            name='last_air_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vkuser',
            name='tv_series',
            field=models.ManyToManyField(blank=True, related_name='vk_users', to='common.TVSeries'),
        ),
    ]
