# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 10:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20170501_1806'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tvseriesvariants',
            unique_together=set([]),
        ),
    ]
