# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20170502_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvseries',
            name='first_air_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
