# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_tvseries_number_of_seasons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvseries',
            name='number_of_seasons',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
